
@rootApi = http://localhost:8000
@userApi = {{rootApi}}/api/v1/user


@burrowApi = {{rootApi}}/api/v1/burrow

@bookApi = {{rootApi}}/api/v1/book

@reviewApi = {{rootApi}}/api/v1/review



### server testing
GET  {{rootApi}}

# ======== user api
### Get user
GET {{userApi}}

### crate  user in db
POST {{userApi}}
Content-Type: application/json

{
    "role": "admin",
    "fName": "Sam",
    "lName": "Smith",
    "phone": "09876",
    "address": "Sydney",
    "email": "suman@gmail.com",
    "password": "123456"
}

# ============ Book api 
### fetch all book
GET {{bookApi}}
Authorization: 64a2b4eb2e7a640a6fa0820a


# ========burrow api
### fetch
GET  {{burrowApi}}
Authorization: 64a9502839d8901cf1488ac4

### create new burrow record

POST {{burrowApi}}
Content-Type: application/json

{
    "bookId": "skfjsj3432",
    "bookName": "Suman Chaudhary",
    "thumbnail": "http://...",
    "userId": "sdkfjdks4534",
    "userName": "how to code",
    "returnDate": "2023-12-12"
}


# ====== review api
### get reviews
GET {{reviewApi}}